general:
  run_name: BigGAN128-FC-z_dim-resnet50-bn-lr5e-6-no_logvar
#  checkpoint_ae: /export/compvis-nfs/user/daltmann/scratch/FCAEModel_512.ckpt # checkpoint for fixed BigGAN in 2nd stage
data:
  aug_deg: 15
  aug_trans: [0.1, 0.1]
  augment_b: 0.4
  augment_c: 0.5
  augment_h: 0.15
  augment_s: 0.4
  augment_wo_dis: true
#  batch_size: 40
  dataset: PlantDataset
  flow_weights: false
  max_frames: 10
  n_pokes: 5
  n_workers: 5
#  normalize_flows: false
  object_weighting: false
  p_col: 0.8
  p_geom: 0.8
  poke_size: 5
  scale_poke_to_res: true
  spatial_size: [128,128]
  split: official
  val_obj_weighting: false
  yield_videos: false
  zero_poke: true
  zero_poke_amount: 12
  filter: all

training:
  lr: 0.000005
  weight_decay: 0
  min_acc_batch_size: 3
#  max_batches_per_epoch: 2000
  max_val_batches: 400
  profiler: False
  n_epochs: 400
  pretrain: 50 # number of epochs before discriminator is included in loss
  w_kl: 0.0001
  val_every: 1500
  forward_sample: False

architecture:
#  n_channels: 2
  deterministic: False
  pretrained: False
  z_dim: 256
  type: resnet18
  norm: bn
  pre_process: False
  use_actnorm_in_dec: False
  n_out_channels: 3
  n_in_channels: 3
  use_adain: False

logging:
  n_val_img_batches: 4
  log_train_prog_at: 300
  n_saved_ckpt: 5
  n_log_images: 4
