architecture:
  kernel_size: [2,3]
  coupling_type: "conv"
  num_steps:
    - 20
    - 8
    - 5
    - 5
    - 3
    - 3
    - 1
  factor: 8
  activation: elu
  transform: affine
  prior_transform: affine
  use1x1: false
  flow_in_channels: 8
  flow_mid_channels: 1536 # = 32*64
  # ----------------VAE config ---------------
  deterministic: false
  nf_in: 2
  min_spatial_size: 8
  nf_max: 8

data:
  aug_deg: 15
  aug_trans: [0.1, 0.1]
  augment_b: 0.4
  augment_c: 0.5
  augment_h: 0.15
  augment_s: 0.4
  augment_wo_dis: true
  # batch_size: 40
  dataset: PlantDataset
  flow_weights: false
  max_frames: 10
  n_pokes: 5
  n_workers: 12
  normalize_flows: false
  object_weighting: false
  p_col: 0.8
  p_geom: 0.8
  poke_size: 5
  scale_poke_to_res: true
  spatial_size: [64,64]
  split: official
  val_obj_weighting: false
  yield_videos: true
  zero_poke: true
  zero_poke_amount: 12
  filter: all

training:
  lr: 0.001
  weight_decay: 0
  lr_scaling: True
  lr_scaling_max_it: 500
  custom_lr_decrease: True




logging:
  log_train_prog_at: 300
  n_samples: 4
  n_log_images: 2
  n_val_img_batches: 2

checkpoint:
  VAE: "/export/scratch/daltmann/flowmotion/flowVAE_8.ckpt"